version: '2'
services:
  prueb0asociados-app:
    image: prueb0asociados
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://prueb0asociados-mysql:3306/prueb0asociados?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://prueb0asociados-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://prueb0asociados-elasticsearch:9200
    ports:
      - 8080:8080
  prueb0asociados-mysql:
    extends:
      file: mysql.yml
      service: prueb0asociados-mysql
  prueb0asociados-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: prueb0asociados-elasticsearch
